### ISSUE TITLE
Dependencies do not exist on GL. 

### ISSUE THREAD

**Issue by mneary1** [radglob/trav_salesman#4]
![screen shot 2014-12-04 at 6 31 45 pm](https://cloud.githubusercontent.com/assets/5521916/5308359/d3688238-7be3-11e4-8567-c01606463240.png)

Just so we're aware, we'll have to submit with the graph just copy/pasted into the files that are solving the TSP.

**Comment by radglob** [comment]
Built a static graph and put it into the nearest_neighbor.py file.

**Comment by radglob** [comment]
Static graphs are boring. I'll just get rid of the random city names and doing something boring.

**Comment by radglob** [comment]
Changed the naming scheme to just concatenate upper case letters as needed. Create a graph to see what I mean.
